Fix compilation failure with dal / audio * arch/arm/mach-msm/qdsp6/q6audio.c:346: undefined reference to `dal_call' etc.
Signed-off-by: spezi77 <spezi77@gmx.com>

Conflicts:
	arch/arm/mach-msm/dal.c